#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TRN")]
public partial class TRNDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTrn(Trn instance);
  partial void UpdateTrn(Trn instance);
  partial void DeleteTrn(Trn instance);
  #endregion
	
	public TRNDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TRNConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TRNDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TRNDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TRNDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TRNDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Trn> Trns
	{
		get
		{
			return this.GetTable<Trn>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchTrn")]
	public ISingleResult<SearchTrnResult> SearchTrn([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="VarChar(50)")] string middleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="Date")] System.Nullable<System.DateTime> dOB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MotherMaiden", DbType="VarChar(50)")] string motherMaiden)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, middleName, lname, dOB, gender, motherMaiden);
		return ((ISingleResult<SearchTrnResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TrnQuery")]
	public ISingleResult<TrnQueryResult> TrnQuery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string query)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), query);
		return ((ISingleResult<TrnQueryResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllTrn")]
	public ISingleResult<SelectAllTrnResult> SelectAllTrn()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectAllTrnResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllTrnById")]
	public ISingleResult<SelectAllTrnByIdResult> SelectAllTrnById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrnNum", DbType="Int")] System.Nullable<int> trnNum)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trnNum);
		return ((ISingleResult<SelectAllTrnByIdResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trn")]
public partial class Trn : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _TrnNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _MotherMaiden;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrnNumChanging(int value);
    partial void OnTrnNumChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLnameChanging(string value);
    partial void OnLnameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnMotherMaidenChanging(string value);
    partial void OnMotherMaidenChanged();
    #endregion
	
	public Trn()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrnNum", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int TrnNum
	{
		get
		{
			return this._TrnNum;
		}
		set
		{
			if ((this._TrnNum != value))
			{
				this.OnTrnNumChanging(value);
				this.SendPropertyChanging();
				this._TrnNum = value;
				this.SendPropertyChanged("TrnNum");
				this.OnTrnNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this.OnFnameChanging(value);
				this.SendPropertyChanging();
				this._Fname = value;
				this.SendPropertyChanged("Fname");
				this.OnFnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this.OnMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._MiddleName = value;
				this.SendPropertyChanged("MiddleName");
				this.OnMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this.OnLnameChanging(value);
				this.SendPropertyChanging();
				this._Lname = value;
				this.SendPropertyChanged("Lname");
				this.OnLnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this.OnMotherMaidenChanging(value);
				this.SendPropertyChanging();
				this._MotherMaiden = value;
				this.SendPropertyChanged("MotherMaiden");
				this.OnMotherMaidenChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class SearchTrnResult
{
	
	private int _TrnNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _MotherMaiden;
	
	public SearchTrnResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrnNum", DbType="Int NOT NULL")]
	public int TrnNum
	{
		get
		{
			return this._TrnNum;
		}
		set
		{
			if ((this._TrnNum != value))
			{
				this._TrnNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
}

public partial class TrnQueryResult
{
	
	private int _TrnNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _MotherMaiden;
	
	public TrnQueryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrnNum", DbType="Int NOT NULL")]
	public int TrnNum
	{
		get
		{
			return this._TrnNum;
		}
		set
		{
			if ((this._TrnNum != value))
			{
				this._TrnNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
}

public partial class SelectAllTrnResult
{
	
	private int _TrnNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _MotherMaiden;
	
	public SelectAllTrnResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrnNum", DbType="Int NOT NULL")]
	public int TrnNum
	{
		get
		{
			return this._TrnNum;
		}
		set
		{
			if ((this._TrnNum != value))
			{
				this._TrnNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
}

public partial class SelectAllTrnByIdResult
{
	
	private int _TrnNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _MotherMaiden;
	
	public SelectAllTrnByIdResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrnNum", DbType="Int NOT NULL")]
	public int TrnNum
	{
		get
		{
			return this._TrnNum;
		}
		set
		{
			if ((this._TrnNum != value))
			{
				this._TrnNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
}
#pragma warning restore 1591
