#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Passport")]
public partial class PASSPORTDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPassport(Passport instance);
  partial void UpdatePassport(Passport instance);
  partial void DeletePassport(Passport instance);
  #endregion
	
	public PASSPORTDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PassportConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PASSPORTDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PASSPORTDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PASSPORTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PASSPORTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Passport> Passports
	{
		get
		{
			return this.GetTable<Passport>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PassportQuery")]
	public ISingleResult<PassportQueryResult> PassportQuery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string query)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), query);
		return ((ISingleResult<PassportQueryResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllPassportById")]
	public ISingleResult<SelectAllPassportByIdResult> SelectAllPassportById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassportNum", DbType="Int")] System.Nullable<int> passportNum)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), passportNum);
		return ((ISingleResult<SelectAllPassportByIdResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchPassport")]
	public ISingleResult<SearchPassportResult> SearchPassport(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="VarChar(50)")] string middleName, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="Date")] System.Nullable<System.DateTime> dOB, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nationality", DbType="VarChar(50)")] string nationality, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryOfBirth", DbType="VarChar(50)")] string countryOfBirth, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CellNum", DbType="Int")] System.Nullable<int> cellNum, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddr", DbType="VarChar(50)")] string emailAddr, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetNum", DbType="Int")] System.Nullable<int> streetNum, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetName", DbType="VarChar(100)")] string streetName, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Parish", DbType="VarChar(50)")] string parish, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MotherMaiden", DbType="VarChar(50)")] string motherMaiden, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateIssued", DbType="DateTime")] System.Nullable<System.DateTime> dateIssued, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateExpired", DbType="DateTime")] System.Nullable<System.DateTime> dateExpired)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, middleName, lname, dOB, gender, nationality, countryOfBirth, cellNum, emailAddr, streetNum, streetName, city, parish, motherMaiden, dateIssued, dateExpired);
		return ((ISingleResult<SearchPassportResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllPassport")]
	public ISingleResult<SelectAllPassportResult> SelectAllPassport()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectAllPassportResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Passport")]
public partial class Passport : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _PassportNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _Nationality;
	
	private string _CountryOfBirth;
	
	private System.Nullable<int> _CellNum;
	
	private string _EmailAddr;
	
	private System.Nullable<int> _StreetNum;
	
	private string _StreetName;
	
	private string _City;
	
	private string _Parish;
	
	private string _MotherMaiden;
	
	private System.Nullable<System.DateTime> _DateIssued;
	
	private System.Nullable<System.DateTime> _DateExpired;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPassportNumChanging(int value);
    partial void OnPassportNumChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLnameChanging(string value);
    partial void OnLnameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnCountryOfBirthChanging(string value);
    partial void OnCountryOfBirthChanged();
    partial void OnCellNumChanging(System.Nullable<int> value);
    partial void OnCellNumChanged();
    partial void OnEmailAddrChanging(string value);
    partial void OnEmailAddrChanged();
    partial void OnStreetNumChanging(System.Nullable<int> value);
    partial void OnStreetNumChanged();
    partial void OnStreetNameChanging(string value);
    partial void OnStreetNameChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnParishChanging(string value);
    partial void OnParishChanged();
    partial void OnMotherMaidenChanging(string value);
    partial void OnMotherMaidenChanged();
    partial void OnDateIssuedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateIssuedChanged();
    partial void OnDateExpiredChanging(System.Nullable<System.DateTime> value);
    partial void OnDateExpiredChanged();
    #endregion
	
	public Passport()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNum", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int PassportNum
	{
		get
		{
			return this._PassportNum;
		}
		set
		{
			if ((this._PassportNum != value))
			{
				this.OnPassportNumChanging(value);
				this.SendPropertyChanging();
				this._PassportNum = value;
				this.SendPropertyChanged("PassportNum");
				this.OnPassportNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this.OnFnameChanging(value);
				this.SendPropertyChanging();
				this._Fname = value;
				this.SendPropertyChanged("Fname");
				this.OnFnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this.OnMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._MiddleName = value;
				this.SendPropertyChanged("MiddleName");
				this.OnMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this.OnLnameChanging(value);
				this.SendPropertyChanging();
				this._Lname = value;
				this.SendPropertyChanged("Lname");
				this.OnLnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
	public string Nationality
	{
		get
		{
			return this._Nationality;
		}
		set
		{
			if ((this._Nationality != value))
			{
				this.OnNationalityChanging(value);
				this.SendPropertyChanging();
				this._Nationality = value;
				this.SendPropertyChanged("Nationality");
				this.OnNationalityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfBirth", DbType="VarChar(50)")]
	public string CountryOfBirth
	{
		get
		{
			return this._CountryOfBirth;
		}
		set
		{
			if ((this._CountryOfBirth != value))
			{
				this.OnCountryOfBirthChanging(value);
				this.SendPropertyChanging();
				this._CountryOfBirth = value;
				this.SendPropertyChanged("CountryOfBirth");
				this.OnCountryOfBirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int")]
	public System.Nullable<int> CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this.OnCellNumChanging(value);
				this.SendPropertyChanging();
				this._CellNum = value;
				this.SendPropertyChanged("CellNum");
				this.OnCellNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="VarChar(50)")]
	public string EmailAddr
	{
		get
		{
			return this._EmailAddr;
		}
		set
		{
			if ((this._EmailAddr != value))
			{
				this.OnEmailAddrChanging(value);
				this.SendPropertyChanging();
				this._EmailAddr = value;
				this.SendPropertyChanged("EmailAddr");
				this.OnEmailAddrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNum", DbType="Int")]
	public System.Nullable<int> StreetNum
	{
		get
		{
			return this._StreetNum;
		}
		set
		{
			if ((this._StreetNum != value))
			{
				this.OnStreetNumChanging(value);
				this.SendPropertyChanging();
				this._StreetNum = value;
				this.SendPropertyChanged("StreetNum");
				this.OnStreetNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(100)")]
	public string StreetName
	{
		get
		{
			return this._StreetName;
		}
		set
		{
			if ((this._StreetName != value))
			{
				this.OnStreetNameChanging(value);
				this.SendPropertyChanging();
				this._StreetName = value;
				this.SendPropertyChanged("StreetName");
				this.OnStreetNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parish", DbType="VarChar(50)")]
	public string Parish
	{
		get
		{
			return this._Parish;
		}
		set
		{
			if ((this._Parish != value))
			{
				this.OnParishChanging(value);
				this.SendPropertyChanging();
				this._Parish = value;
				this.SendPropertyChanged("Parish");
				this.OnParishChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this.OnMotherMaidenChanging(value);
				this.SendPropertyChanging();
				this._MotherMaiden = value;
				this.SendPropertyChanged("MotherMaiden");
				this.OnMotherMaidenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateIssued
	{
		get
		{
			return this._DateIssued;
		}
		set
		{
			if ((this._DateIssued != value))
			{
				this.OnDateIssuedChanging(value);
				this.SendPropertyChanging();
				this._DateIssued = value;
				this.SendPropertyChanged("DateIssued");
				this.OnDateIssuedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateExpired
	{
		get
		{
			return this._DateExpired;
		}
		set
		{
			if ((this._DateExpired != value))
			{
				this.OnDateExpiredChanging(value);
				this.SendPropertyChanging();
				this._DateExpired = value;
				this.SendPropertyChanged("DateExpired");
				this.OnDateExpiredChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class PassportQueryResult
{
	
	private int _PassportNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _Nationality;
	
	private string _CountryOfBirth;
	
	private System.Nullable<int> _CellNum;
	
	private string _EmailAddr;
	
	private System.Nullable<int> _StreetNum;
	
	private string _StreetName;
	
	private string _City;
	
	private string _Parish;
	
	private string _MotherMaiden;
	
	private System.Nullable<System.DateTime> _DateIssued;
	
	private System.Nullable<System.DateTime> _DateExpired;
	
	public PassportQueryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNum", DbType="Int NOT NULL")]
	public int PassportNum
	{
		get
		{
			return this._PassportNum;
		}
		set
		{
			if ((this._PassportNum != value))
			{
				this._PassportNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
	public string Nationality
	{
		get
		{
			return this._Nationality;
		}
		set
		{
			if ((this._Nationality != value))
			{
				this._Nationality = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfBirth", DbType="VarChar(50)")]
	public string CountryOfBirth
	{
		get
		{
			return this._CountryOfBirth;
		}
		set
		{
			if ((this._CountryOfBirth != value))
			{
				this._CountryOfBirth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int")]
	public System.Nullable<int> CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="VarChar(50)")]
	public string EmailAddr
	{
		get
		{
			return this._EmailAddr;
		}
		set
		{
			if ((this._EmailAddr != value))
			{
				this._EmailAddr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNum", DbType="Int")]
	public System.Nullable<int> StreetNum
	{
		get
		{
			return this._StreetNum;
		}
		set
		{
			if ((this._StreetNum != value))
			{
				this._StreetNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(100)")]
	public string StreetName
	{
		get
		{
			return this._StreetName;
		}
		set
		{
			if ((this._StreetName != value))
			{
				this._StreetName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parish", DbType="VarChar(50)")]
	public string Parish
	{
		get
		{
			return this._Parish;
		}
		set
		{
			if ((this._Parish != value))
			{
				this._Parish = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateIssued
	{
		get
		{
			return this._DateIssued;
		}
		set
		{
			if ((this._DateIssued != value))
			{
				this._DateIssued = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateExpired
	{
		get
		{
			return this._DateExpired;
		}
		set
		{
			if ((this._DateExpired != value))
			{
				this._DateExpired = value;
			}
		}
	}
}

public partial class SelectAllPassportByIdResult
{
	
	private int _PassportNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _Nationality;
	
	private string _CountryOfBirth;
	
	private System.Nullable<int> _CellNum;
	
	private string _EmailAddr;
	
	private System.Nullable<int> _StreetNum;
	
	private string _StreetName;
	
	private string _City;
	
	private string _Parish;
	
	private string _MotherMaiden;
	
	private System.Nullable<System.DateTime> _DateIssued;
	
	private System.Nullable<System.DateTime> _DateExpired;
	
	public SelectAllPassportByIdResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNum", DbType="Int NOT NULL")]
	public int PassportNum
	{
		get
		{
			return this._PassportNum;
		}
		set
		{
			if ((this._PassportNum != value))
			{
				this._PassportNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
	public string Nationality
	{
		get
		{
			return this._Nationality;
		}
		set
		{
			if ((this._Nationality != value))
			{
				this._Nationality = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfBirth", DbType="VarChar(50)")]
	public string CountryOfBirth
	{
		get
		{
			return this._CountryOfBirth;
		}
		set
		{
			if ((this._CountryOfBirth != value))
			{
				this._CountryOfBirth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int")]
	public System.Nullable<int> CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="VarChar(50)")]
	public string EmailAddr
	{
		get
		{
			return this._EmailAddr;
		}
		set
		{
			if ((this._EmailAddr != value))
			{
				this._EmailAddr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNum", DbType="Int")]
	public System.Nullable<int> StreetNum
	{
		get
		{
			return this._StreetNum;
		}
		set
		{
			if ((this._StreetNum != value))
			{
				this._StreetNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(100)")]
	public string StreetName
	{
		get
		{
			return this._StreetName;
		}
		set
		{
			if ((this._StreetName != value))
			{
				this._StreetName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parish", DbType="VarChar(50)")]
	public string Parish
	{
		get
		{
			return this._Parish;
		}
		set
		{
			if ((this._Parish != value))
			{
				this._Parish = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateIssued
	{
		get
		{
			return this._DateIssued;
		}
		set
		{
			if ((this._DateIssued != value))
			{
				this._DateIssued = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateExpired
	{
		get
		{
			return this._DateExpired;
		}
		set
		{
			if ((this._DateExpired != value))
			{
				this._DateExpired = value;
			}
		}
	}
}

public partial class SearchPassportResult
{
	
	private int _PassportNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _Nationality;
	
	private string _CountryOfBirth;
	
	private System.Nullable<int> _CellNum;
	
	private string _EmailAddr;
	
	private System.Nullable<int> _StreetNum;
	
	private string _StreetName;
	
	private string _City;
	
	private string _Parish;
	
	private string _MotherMaiden;
	
	private System.Nullable<System.DateTime> _DateIssued;
	
	private System.Nullable<System.DateTime> _DateExpired;
	
	public SearchPassportResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNum", DbType="Int NOT NULL")]
	public int PassportNum
	{
		get
		{
			return this._PassportNum;
		}
		set
		{
			if ((this._PassportNum != value))
			{
				this._PassportNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
	public string Nationality
	{
		get
		{
			return this._Nationality;
		}
		set
		{
			if ((this._Nationality != value))
			{
				this._Nationality = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfBirth", DbType="VarChar(50)")]
	public string CountryOfBirth
	{
		get
		{
			return this._CountryOfBirth;
		}
		set
		{
			if ((this._CountryOfBirth != value))
			{
				this._CountryOfBirth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int")]
	public System.Nullable<int> CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="VarChar(50)")]
	public string EmailAddr
	{
		get
		{
			return this._EmailAddr;
		}
		set
		{
			if ((this._EmailAddr != value))
			{
				this._EmailAddr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNum", DbType="Int")]
	public System.Nullable<int> StreetNum
	{
		get
		{
			return this._StreetNum;
		}
		set
		{
			if ((this._StreetNum != value))
			{
				this._StreetNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(100)")]
	public string StreetName
	{
		get
		{
			return this._StreetName;
		}
		set
		{
			if ((this._StreetName != value))
			{
				this._StreetName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parish", DbType="VarChar(50)")]
	public string Parish
	{
		get
		{
			return this._Parish;
		}
		set
		{
			if ((this._Parish != value))
			{
				this._Parish = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateIssued
	{
		get
		{
			return this._DateIssued;
		}
		set
		{
			if ((this._DateIssued != value))
			{
				this._DateIssued = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateExpired
	{
		get
		{
			return this._DateExpired;
		}
		set
		{
			if ((this._DateExpired != value))
			{
				this._DateExpired = value;
			}
		}
	}
}

public partial class SelectAllPassportResult
{
	
	private int _PassportNum;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _Gender;
	
	private string _Nationality;
	
	private string _CountryOfBirth;
	
	private System.Nullable<int> _CellNum;
	
	private string _EmailAddr;
	
	private System.Nullable<int> _StreetNum;
	
	private string _StreetName;
	
	private string _City;
	
	private string _Parish;
	
	private string _MotherMaiden;
	
	private System.Nullable<System.DateTime> _DateIssued;
	
	private System.Nullable<System.DateTime> _DateExpired;
	
	public SelectAllPassportResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNum", DbType="Int NOT NULL")]
	public int PassportNum
	{
		get
		{
			return this._PassportNum;
		}
		set
		{
			if ((this._PassportNum != value))
			{
				this._PassportNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50)")]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50)")]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
	public string Nationality
	{
		get
		{
			return this._Nationality;
		}
		set
		{
			if ((this._Nationality != value))
			{
				this._Nationality = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfBirth", DbType="VarChar(50)")]
	public string CountryOfBirth
	{
		get
		{
			return this._CountryOfBirth;
		}
		set
		{
			if ((this._CountryOfBirth != value))
			{
				this._CountryOfBirth = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int")]
	public System.Nullable<int> CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddr", DbType="VarChar(50)")]
	public string EmailAddr
	{
		get
		{
			return this._EmailAddr;
		}
		set
		{
			if ((this._EmailAddr != value))
			{
				this._EmailAddr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetNum", DbType="Int")]
	public System.Nullable<int> StreetNum
	{
		get
		{
			return this._StreetNum;
		}
		set
		{
			if ((this._StreetNum != value))
			{
				this._StreetNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(100)")]
	public string StreetName
	{
		get
		{
			return this._StreetName;
		}
		set
		{
			if ((this._StreetName != value))
			{
				this._StreetName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this._City = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parish", DbType="VarChar(50)")]
	public string Parish
	{
		get
		{
			return this._Parish;
		}
		set
		{
			if ((this._Parish != value))
			{
				this._Parish = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50)")]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateIssued
	{
		get
		{
			return this._DateIssued;
		}
		set
		{
			if ((this._DateIssued != value))
			{
				this._DateIssued = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateExpired", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateExpired
	{
		get
		{
			return this._DateExpired;
		}
		set
		{
			if ((this._DateExpired != value))
			{
				this._DateExpired = value;
			}
		}
	}
}
#pragma warning restore 1591
