#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Identifiers")]
public partial class IDENTIFIERSDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertPerson(Person instance);
  partial void UpdatePerson(Person instance);
  partial void DeletePerson(Person instance);
  #endregion
	
	public IDENTIFIERSDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["IdentifiersConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public IDENTIFIERSDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public IDENTIFIERSDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public IDENTIFIERSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public IDENTIFIERSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Person> Persons
	{
		get
		{
			return this.GetTable<Person>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PersonQuery")]
	public ISingleResult<PersonQueryResult> PersonQuery([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(300)")] string query)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), query);
		return ((ISingleResult<PersonQueryResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllPerson")]
	public ISingleResult<SelectAllPersonResult> SelectAllPerson()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<SelectAllPersonResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectAllPersonById")]
	public ISingleResult<SelectAllPersonByIdResult> SelectAllPersonById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustID", DbType="Int")] System.Nullable<int> custID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), custID);
		return ((ISingleResult<SelectAllPersonByIdResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchPerson")]
	public ISingleResult<SearchPersonResult> SearchPerson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="VarChar(50)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="VarChar(50)")] string middleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="VarChar(50)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="DateTime")] System.Nullable<System.DateTime> dOB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(10)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Addr", DbType="VarChar(100)")] string addr, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MotherMaiden", DbType="VarChar(50)")] string motherMaiden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CellNum", DbType="Int")] System.Nullable<int> cellNum)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname, middleName, lname, dOB, gender, addr, motherMaiden, email, cellNum);
		return ((ISingleResult<SearchPersonResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CustID;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.DateTime _DOB;
	
	private string _Gender;
	
	private string _Addr;
	
	private string _MotherMaiden;
	
	private string _Email;
	
	private int _CellNum;
	
	private string _TRN;
	
	private string _Passport;
	
	private string _NAtionID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustIDChanging(int value);
    partial void OnCustIDChanged();
    partial void OnFnameChanging(string value);
    partial void OnFnameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLnameChanging(string value);
    partial void OnLnameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAddrChanging(string value);
    partial void OnAddrChanged();
    partial void OnMotherMaidenChanging(string value);
    partial void OnMotherMaidenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCellNumChanging(int value);
    partial void OnCellNumChanged();
    partial void OnTRNChanging(string value);
    partial void OnTRNChanged();
    partial void OnPassportChanging(string value);
    partial void OnPassportChanged();
    partial void OnNAtionIDChanging(string value);
    partial void OnNAtionIDChanged();
    #endregion
	
	public Person()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int CustID
	{
		get
		{
			return this._CustID;
		}
		set
		{
			if ((this._CustID != value))
			{
				this.OnCustIDChanging(value);
				this.SendPropertyChanging();
				this._CustID = value;
				this.SendPropertyChanged("CustID");
				this.OnCustIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this.OnFnameChanging(value);
				this.SendPropertyChanging();
				this._Fname = value;
				this.SendPropertyChanged("Fname");
				this.OnFnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this.OnMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._MiddleName = value;
				this.SendPropertyChanged("MiddleName");
				this.OnMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this.OnLnameChanging(value);
				this.SendPropertyChanging();
				this._Lname = value;
				this.SendPropertyChanged("Lname");
				this.OnLnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Addr
	{
		get
		{
			return this._Addr;
		}
		set
		{
			if ((this._Addr != value))
			{
				this.OnAddrChanging(value);
				this.SendPropertyChanging();
				this._Addr = value;
				this.SendPropertyChanged("Addr");
				this.OnAddrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this.OnMotherMaidenChanging(value);
				this.SendPropertyChanging();
				this._MotherMaiden = value;
				this.SendPropertyChanged("MotherMaiden");
				this.OnMotherMaidenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int NOT NULL")]
	public int CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this.OnCellNumChanging(value);
				this.SendPropertyChanging();
				this._CellNum = value;
				this.SendPropertyChanged("CellNum");
				this.OnCellNumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN", DbType="VarChar(50)")]
	public string TRN
	{
		get
		{
			return this._TRN;
		}
		set
		{
			if ((this._TRN != value))
			{
				this.OnTRNChanging(value);
				this.SendPropertyChanging();
				this._TRN = value;
				this.SendPropertyChanged("TRN");
				this.OnTRNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
	public string Passport
	{
		get
		{
			return this._Passport;
		}
		set
		{
			if ((this._Passport != value))
			{
				this.OnPassportChanging(value);
				this.SendPropertyChanging();
				this._Passport = value;
				this.SendPropertyChanged("Passport");
				this.OnPassportChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAtionID", DbType="VarChar(50)")]
	public string NAtionID
	{
		get
		{
			return this._NAtionID;
		}
		set
		{
			if ((this._NAtionID != value))
			{
				this.OnNAtionIDChanging(value);
				this.SendPropertyChanging();
				this._NAtionID = value;
				this.SendPropertyChanged("NAtionID");
				this.OnNAtionIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class PersonQueryResult
{
	
	private int _CustID;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.DateTime _DOB;
	
	private string _Gender;
	
	private string _Addr;
	
	private string _MotherMaiden;
	
	private string _Email;
	
	private int _CellNum;
	
	private string _TRN;
	
	private string _Passport;
	
	private string _NAtionID;
	
	public PersonQueryResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL")]
	public int CustID
	{
		get
		{
			return this._CustID;
		}
		set
		{
			if ((this._CustID != value))
			{
				this._CustID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Addr
	{
		get
		{
			return this._Addr;
		}
		set
		{
			if ((this._Addr != value))
			{
				this._Addr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int NOT NULL")]
	public int CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN", DbType="VarChar(50)")]
	public string TRN
	{
		get
		{
			return this._TRN;
		}
		set
		{
			if ((this._TRN != value))
			{
				this._TRN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
	public string Passport
	{
		get
		{
			return this._Passport;
		}
		set
		{
			if ((this._Passport != value))
			{
				this._Passport = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAtionID", DbType="VarChar(50)")]
	public string NAtionID
	{
		get
		{
			return this._NAtionID;
		}
		set
		{
			if ((this._NAtionID != value))
			{
				this._NAtionID = value;
			}
		}
	}
}

public partial class SelectAllPersonResult
{
	
	private int _CustID;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.DateTime _DOB;
	
	private string _Gender;
	
	private string _Addr;
	
	private string _MotherMaiden;
	
	private string _Email;
	
	private int _CellNum;
	
	private string _TRN;
	
	private string _Passport;
	
	private string _NAtionID;
	
	public SelectAllPersonResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL")]
	public int CustID
	{
		get
		{
			return this._CustID;
		}
		set
		{
			if ((this._CustID != value))
			{
				this._CustID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Addr
	{
		get
		{
			return this._Addr;
		}
		set
		{
			if ((this._Addr != value))
			{
				this._Addr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int NOT NULL")]
	public int CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN", DbType="VarChar(50)")]
	public string TRN
	{
		get
		{
			return this._TRN;
		}
		set
		{
			if ((this._TRN != value))
			{
				this._TRN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
	public string Passport
	{
		get
		{
			return this._Passport;
		}
		set
		{
			if ((this._Passport != value))
			{
				this._Passport = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAtionID", DbType="VarChar(50)")]
	public string NAtionID
	{
		get
		{
			return this._NAtionID;
		}
		set
		{
			if ((this._NAtionID != value))
			{
				this._NAtionID = value;
			}
		}
	}
}

public partial class SelectAllPersonByIdResult
{
	
	private int _CustID;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.DateTime _DOB;
	
	private string _Gender;
	
	private string _Addr;
	
	private string _MotherMaiden;
	
	private string _Email;
	
	private int _CellNum;
	
	private string _TRN;
	
	private string _Passport;
	
	private string _NAtionID;
	
	public SelectAllPersonByIdResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL")]
	public int CustID
	{
		get
		{
			return this._CustID;
		}
		set
		{
			if ((this._CustID != value))
			{
				this._CustID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Addr
	{
		get
		{
			return this._Addr;
		}
		set
		{
			if ((this._Addr != value))
			{
				this._Addr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int NOT NULL")]
	public int CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN", DbType="VarChar(50)")]
	public string TRN
	{
		get
		{
			return this._TRN;
		}
		set
		{
			if ((this._TRN != value))
			{
				this._TRN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
	public string Passport
	{
		get
		{
			return this._Passport;
		}
		set
		{
			if ((this._Passport != value))
			{
				this._Passport = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAtionID", DbType="VarChar(50)")]
	public string NAtionID
	{
		get
		{
			return this._NAtionID;
		}
		set
		{
			if ((this._NAtionID != value))
			{
				this._NAtionID = value;
			}
		}
	}
}

public partial class SearchPersonResult
{
	
	private int _CustID;
	
	private string _Fname;
	
	private string _MiddleName;
	
	private string _Lname;
	
	private System.DateTime _DOB;
	
	private string _Gender;
	
	private string _Addr;
	
	private string _MotherMaiden;
	
	private string _Email;
	
	private int _CellNum;
	
	private string _TRN;
	
	private string _Passport;
	
	private string _NAtionID;
	
	public SearchPersonResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustID", DbType="Int NOT NULL")]
	public int CustID
	{
		get
		{
			return this._CustID;
		}
		set
		{
			if ((this._CustID != value))
			{
				this._CustID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Fname
	{
		get
		{
			return this._Fname;
		}
		set
		{
			if ((this._Fname != value))
			{
				this._Fname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
	public string MiddleName
	{
		get
		{
			return this._MiddleName;
		}
		set
		{
			if ((this._MiddleName != value))
			{
				this._MiddleName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Lname
	{
		get
		{
			return this._Lname;
		}
		set
		{
			if ((this._Lname != value))
			{
				this._Lname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date NOT NULL")]
	public System.DateTime DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this._DOB = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addr", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Addr
	{
		get
		{
			return this._Addr;
		}
		set
		{
			if ((this._Addr != value))
			{
				this._Addr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMaiden", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string MotherMaiden
	{
		get
		{
			return this._MotherMaiden;
		}
		set
		{
			if ((this._MotherMaiden != value))
			{
				this._MotherMaiden = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNum", DbType="Int NOT NULL")]
	public int CellNum
	{
		get
		{
			return this._CellNum;
		}
		set
		{
			if ((this._CellNum != value))
			{
				this._CellNum = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRN", DbType="VarChar(50)")]
	public string TRN
	{
		get
		{
			return this._TRN;
		}
		set
		{
			if ((this._TRN != value))
			{
				this._TRN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passport", DbType="VarChar(50)")]
	public string Passport
	{
		get
		{
			return this._Passport;
		}
		set
		{
			if ((this._Passport != value))
			{
				this._Passport = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAtionID", DbType="VarChar(50)")]
	public string NAtionID
	{
		get
		{
			return this._NAtionID;
		}
		set
		{
			if ((this._NAtionID != value))
			{
				this._NAtionID = value;
			}
		}
	}
}
#pragma warning restore 1591
