<?xml version="1.0" encoding="utf-8"?><Database Name="National" Class="NATIONALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CHRISTOPHER-PC;Initial Catalog=National;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NationalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NatID" Member="NatIDs">
    <Type Name="NatID">
      <Column Name="NatIDNum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotherMaiden" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.NatIDQuery" Method="NatIDQuery">
    <Parameter Name="query" Type="System.String" DbType="VarChar(300)" />
    <ElementType Name="NatIDQueryResult">
      <Column Name="NatIDNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotherMaiden" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectAllNatIDById" Method="SelectAllNatIDById">
    <Parameter Name="NatIDNum" Parameter="natIDNum" Type="System.Int32" DbType="Int" />
    <ElementType Name="SelectAllNatIDByIdResult">
      <Column Name="NatIDNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotherMaiden" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SearchNatID" Method="SearchNatID">
    <Parameter Name="Fname" Parameter="fname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MiddleName" Parameter="middleName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Lname" Parameter="lname" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MotherMaiden" Parameter="motherMaiden" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SearchNatIDResult">
      <Column Name="NatIDNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotherMaiden" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectAllNatID" Method="SelectAllNatID">
    <ElementType Name="SelectAllNatIDResult">
      <Column Name="NatIDNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MotherMaiden" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>